[package]
authors = ["Félix Saparelli <felix@passcod.name>"]
name = "fromvalue-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"

[dependencies.fromvalue]
path = "../fromvalue"
